# Generated by Django 6.1.1 on 2026-09-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ganaderia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comprador', models.CharField(blank=True, max_length=150, null=True)),
                ('peso_total_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_animales', models.IntegerField()),
                ('costo_reconocido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utilidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalle', to='ganaderia.lote')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'detalle_venta',
            },
        ),
    ]
