# Generated by Django 6.1.1 on 2026-09-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='ingreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='costo_reconocido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
