# Generated by Django 6.1.1 on 2026-09-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ganaderia', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan de Consumo',
                'verbose_name_plural': 'Planes de Consumo',
                'db_table': 'plan_consumo',
            },
        ),
        migrations.CreateModel(
            name='DetallePlanConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_diaria', models.DecimalField(decimal_places=3, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.unidadmedida')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='alimentacion.planconsumo')),
            ],
            options={
                'verbose_name': 'Detalle de Plan de Consumo',
                'verbose_name_plural': 'Detalles de Planes de Consumo',
                'db_table': 'detalle_plan_consumo',
            },
        ),
        migrations.CreateModel(
            name='AsignacionPlanLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_plan', to='ganaderia.lote')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alimentacion.planconsumo')),
            ],
            options={
                'verbose_name': 'Asignación de Plan a Lote',
                'verbose_name_plural': 'Asignaciones de Planes a Lotes',
                'db_table': 'asignacion_plan_lote',
            },
        ),
    ]
