# Generated by Django 6.1.1 on 2026-09-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ganaderia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compra de Animales',
                'verbose_name_plural': 'Compras de Animales',
                'db_table': 'compra_animal',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompraAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_adquisicion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ganaderia.animal')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compra_animales.compraanimal')),
            ],
            options={
                'verbose_name': 'Detalle de Compra de Animal',
                'verbose_name_plural': 'Detalles de Compra de Animales',
                'db_table': 'detalle_compra_animal',
            },
        ),
        migrations.AddField(
            model_name='compraanimal',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compra_animales.proveedor'),
        ),
    ]
